CookBook

--------第一章--------
Python 3.7.4 (default, Aug  9 2019, 18:34:13) [MSC v.1915 64 bit (AMD64)]
Type "copyright", "credits" or "license" for more information.

IPython 7.8.0 -- An enhanced Interactive Python.

w=[1,1,1,2,2,3]

from collections import Counter

wc=Counter(w)

a=wc.most_common(2)

a
Out[5]: [(1, 3), (2, 2)]

wc.update()

wc
Out[7]: Counter({1: 3, 2: 2, 3: 1})

class User:
    def_init_(self,user_id)
    self.user_id=user_id
    def  _repr_(self):
        return 'User({})'.format(self.user_id)
        
Traceback (most recent call last):

  File "<ipython-input-8-c8b9ca250f7c>", line 1, in <module>
    class User:

  File "<ipython-input-8-c8b9ca250f7c>", line 2, in User
    def_init_(self,user_id)

NameError: name 'def_init_' is not defined




class User:
    def__init__(self,user_id)
    self.user_id=user_id
    def  __repr__(self):
        return 'User({})'.format(self.user_id)
        
Traceback (most recent call last):

  File "<ipython-input-9-7cd6e6810379>", line 1, in <module>
    class User:

  File "<ipython-input-9-7cd6e6810379>", line 2, in User
    def__init__(self,user_id)

NameError: name 'def__init__' is not defined




class User:
    def __init__(self,user_id)
    self.user_id=user_id
    def  __repr__(self):
        return 'User({})'.format(self.user_id)
  File "<ipython-input-10-894c834986f6>", line 2
    def __init__(self,user_id)
                              ^
SyntaxError: invalid syntax




class User:
    def __init__(self,user_id):
        self.user_id=user_id
    def  __repr__(self):
        return 'User({})'.format(self.user_id)
        

users=[User(23),user(3),User(99)]
Traceback (most recent call last):

  File "<ipython-input-12-7645bd143d45>", line 1, in <module>
    users=[User(23),user(3),User(99)]

NameError: name 'user' is not defined




users=[User(23),User(3),User(99)]

sorted(users,key=lambda u: u,user_id)
  File "<ipython-input-14-5c8fe9ed8fad>", line 1
    sorted(users,key=lambda u: u,user_id)
                                ^
SyntaxError: positional argument follows keyword argument




sorted(users,key=lambda u: u.user_id)
Out[15]: [User(3), User(23), User(99)]

from operator import attrgetter

sorted(users,key=attrgetter('user_id'))
Out[17]: [User(3), User(23), User(99)]

min(user,key=attrgetter('user_name'))
Traceback (most recent call last):

  File "<ipython-input-18-9a9e70eb7113>", line 1, in <module>
    min(user,key=attrgetter('user_name'))

NameError: name 'user' is not defined




min(usesr,key=attrgetter('user_name'))
Traceback (most recent call last):

  File "<ipython-input-19-f83322a96f15>", line 1, in <module>
    min(usesr,key=attrgetter('user_name'))

NameError: name 'usesr' is not defined




min(users,key=attrgetter('user_name'))
Traceback (most recent call last):

  File "<ipython-input-20-2de890a3f6ee>", line 1, in <module>
    min(users,key=attrgetter('user_name'))

AttributeError: 'User' object has no attribute 'user_name'




min(users,key=attrgetter('user_id'))
Out[21]: User(3)

man(users,key=attrgetter('user_id'))
Traceback (most recent call last):

  File "<ipython-input-22-95390105d206>", line 1, in <module>
    man(users,key=attrgetter('user_id'))

NameError: name 'man' is not defined




max(users,key=attrgetter('user_id'))
Out[23]: User(99)

rows=[
{'address':'5412 CLARK','date':'07/01/2012'},
{'address':'1412 CLARK','date':'07/01/2016'},
{'address':'2412 CLARK','date':'07/01/2019'}]

from operator import itemgetter

from itertools import groupby

row.sort(key=itemgetter('data'))
Traceback (most recent call last):

  File "<ipython-input-27-ffe702f8eb0d>", line 1, in <module>
    row.sort(key=itemgetter('data'))

NameError: name 'row' is not defined




rows.sort(key=itemgetter('data'))
Traceback (most recent call last):

  File "<ipython-input-28-ded3f87680e0>", line 1, in <module>
    rows.sort(key=itemgetter('data'))

KeyError: 'data'




rows.sort(key=itemgetter('date'))

rows
Out[30]: 
[{'address': '5412 CLARK', 'date': '07/01/2012'},
 {'address': '1412 CLARK', 'date': '07/01/2016'},
 {'address': '2412 CLARK', 'date': '07/01/2019'}]

from date,items in groupby(rows,key=itemgetter('date')):
    print(date)
  File "<ipython-input-31-ded8b3e4eaf1>", line 1
    from date,items in groupby(rows,key=itemgetter('date')):
             ^
SyntaxError: invalid syntax




from date,items in groupby(rows,key=itemgetter('date')):
    print(date)/
  File "<ipython-input-32-4dd3b05cfc92>", line 1
    from date,items in groupby(rows,key=itemgetter('date')):
             ^
SyntaxError: invalid syntax




from date,items in groupby(rows,key=itemgetter('date'))
    print(date)\
    for i in items:
        print('  ',i)
  File "<ipython-input-33-e9dafca7d617>", line 1
    from date,items in groupby(rows,key=itemgetter('date'))
             ^
SyntaxError: invalid syntax




from date,items in groupby(rows ,key=itemgetter('date'))
    print(date)\ 
    for i in items:
        print('  ',i)
  File "<ipython-input-34-d2edb808cae3>", line 1
    from date,items in groupby(rows ,key=itemgetter('date'))
             ^
SyntaxError: invalid syntax




runfile('C:/Users/16476/untitled0.py', wdir='C:/Users/16476')
Traceback (most recent call last):

  File "d:\Users\16476\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 3326, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)

  File "<ipython-input-35-a188ba00e4e9>", line 1, in <module>
    runfile('C:/Users/16476/untitled0.py', wdir='C:/Users/16476')

  File "d:\Users\16476\Anaconda3\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 827, in runfile
    execfile(filename, namespace)

  File "d:\Users\16476\Anaconda3\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 110, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "C:/Users/16476/untitled0.py", line 9
    print('  ',i)
                 
^
SyntaxError: EOF while scanning triple-quoted string literal




from date,items in groupby(rows ,key=itemgetter('date')):
    print(date)\ 
    for i in items:
        print('  ',i)
  File "<ipython-input-36-665a94da095b>", line 1
    from date,items in groupby(rows ,key=itemgetter('date')):
             ^
SyntaxError: invalid syntax




from date,items in groupby(rows,key=itemgetter('date')):
    print(date)\
    for i in items:
        print('  ',i)
  File "<ipython-input-37-98ac19b98562>", line 1
    from date,items in groupby(rows,key=itemgetter('date')):
             ^
SyntaxError: invalid syntax




for date,items in groupby(rows,key=itemgetter('date')):
    print(date)\
    for i in items:
        print('  ',i)
  File "<ipython-input-38-043ef2cbeca1>", line 3
    for i in items:
      ^
SyntaxError: invalid syntax




for date,items in groupby(rows,key=itemgetter('date')):
    print(date)
    for i in items:
        print('  ',i) 
        
07/01/2012
   {'address': '5412 CLARK', 'date': '07/01/2012'}
07/01/2016
   {'address': '1412 CLARK', 'date': '07/01/2016'}
07/01/2019
   {'address': '2412 CLARK', 'date': '07/01/2019'}
 from collections import namedtuple

s=namedtuple('S',['A''B'])

s=namedtuple('Sb',['A''B'])

s
Out[49]: __main__.Sb

sb
Traceback (most recent call last):

  File "<ipython-input-50-2e29fd6b6233>", line 1, in <module>
    sb

NameError: name 'sb' is not defined




Sb
Traceback (most recent call last):

  File "<ipython-input-51-09d66f3f1d43>", line 1, in <module>
    Sb

NameError: name 'Sb' is not defined




sub=s('c','d')
Traceback (most recent call last):

  File "<ipython-input-52-b9ab37554950>", line 1, in <module>
    sub=s('c','d')

TypeError: __new__() takes 2 positional arguments but 3 were given




s=namedtuple('s',['A''B'])

sc=s('c','d')
Traceback (most recent call last):

  File "<ipython-input-54-c37c11b9961a>", line 1, in <module>
    sc=s('c','d')

TypeError: __new__() takes 2 positional arguments but 3 were given




sc=('c')

sc
Out[56]: 'c'

sc=s('s')

sc
Out[58]: s(AB='s')

import numpy as np

np.random.randint(10,size=10)
Out[60]: array([7, 7, 3, 7, 3, 5, 0, 2, 4, 4])

a=np.random.randint(10,size=10)

a
Out[62]: array([9, 2, 9, 1, 3, 8, 6, 6, 7, 0])

s=sum(a)

s
Out[64]: 51

s=sum(x**x for x in a)

s
Out[66]: 792535082

   



import os

file=os.listdir('dirname')
Traceback (most recent call last):

  File "<ipython-input-68-ffd0d57c2f8d>", line 1, in <module>
    file=os.listdir('dirname')

FileNotFoundError: [WinError 3] 系统找不到指定的路径。: 'dirname'




file=os.listdir('%dirs')
Traceback (most recent call last):

  File "<ipython-input-69-73428e3e7cb8>", line 1, in <module>
    file=os.listdir('%dirs')

FileNotFoundError: [WinError 3] 系统找不到指定的路径。: '%dirs'




file=os.listdir()

file
Out[71]: 
['.anaconda',
 '.android',
 '.AndroidStudio3.2',
 '.bash_history',
 '.BigNox',
 '.conda',
 '.condarc',
 '.config',
 '.emulator_console_auth_token',
 '.gitconfig',
 '.gradle',
 '.idlerc',
 '.ipython',
 '.LdVirtualBox',
 '.matplotlib',
 '.spyder-py3',
 '.ssh',
 '.VirtualBox',
 'AndroidStudioProjects',
 'AppData',
 'Application Data',
 'Contacts',
 'Cookies',
 'd4ac4633ebd6440fa397b84f1bc94a3c.7z',
 'Favorites',
 'Foxit Reader SDK ActiveX.ini',
 'Hello.java',
 'inittk.ini',
 'inst.ini',
 'IntelGraphicsProfiles',
 'Links',
 'Local Settings',
 'MicrosoftEdgeBackups',
 'Music',
 'My Documents',
 'NetHood',
 'Nox_share',
 'NTUSER.DAT',
 'ntuser.dat.LOG1',
 'ntuser.dat.LOG2',
 'NTUSER.DAT{acf20663-1ba4-11e8-83d4-f894c2bd03de}.TM.blf',
 'NTUSER.DAT{acf20663-1ba4-11e8-83d4-f894c2bd03de}.TMContainer00000000000000000001.regtrans-ms',
 'NTUSER.DAT{acf20663-1ba4-11e8-83d4-f894c2bd03de}.TMContainer00000000000000000002.regtrans-ms',
 'ntuser.ini',
 'ntuser.pol',
 'nuuid.ini',
 'Pictures',
 'pip',
 'PrintHood',
 'python123demo',
 'Recent',
 'Saved Games',
 'scikit_learn_data',
 'Searches',
 'SendTo',
 'skb.kc',
 'source',
 'Templates',
 'UnblockNeteaseMusic-master',
 'untitled0.py',
 'useruid.ini',
 'Videos',
 'VirtualBox VMs',
 'vmlogs',
 '「开始」菜单']

s=('acme'50,,123.45)
  File "<ipython-input-72-d18d344791bb>", line 1
    s=('acme'50,,123.45)
              ^
SyntaxError: invalid syntax




s=('acme',50,123.45)

print(','.join(str(x) for x in s))
acme,50,123.45

a={'x':1'y':2}
  File "<ipython-input-75-f88a488f0b98>", line 1
    a={'x':1'y':2}
              ^
SyntaxError: invalid syntax




a={'x':1,'y':2}

a
Out[77]: {'x': 1, 'y': 2}

b={'y':3,'z':4}

from collections import ChainMap

c=ChainMap(a,b)

c
Out[81]: ChainMap({'x': 1, 'y': 2}, {'y': 3, 'z': 4})

--------第二章--------
